import "./globals.css";
import type { Metadata } from "next";
import { Figtree, Merriweather, Poppins } from "next/font/google";

const josefin_Sans = Figtree({
  style: ["normal"],
  subsets: ["latin"],
});

const merriweather = Poppins({
  style: "normal",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={merriweather.className}>{children}</body>
    </html>
  );
}
